### ISSUE TITLE
NoMethodError - undefined method `*' for nil:NilClass Error during install

### ISSUE THREAD

**Issue by squarefrog** [orta/cocoapods-keys#113]
I added `cocoapods-keys` to a project today, and had a slight issue with initial install. 

```
$ gem install cocoapods-keys
$ vim Podfile
$ pod install
CocoaPods-Keys has detected a keys mismatch for your setup.
 What is the key for TraktAPIKey
 > ABCDEF123456789 

Saved TraktAPIKey to TraktTopTen.
```

All well and good, but then immediately after I got the following issue:

------ 

### Command

```
/Users/pi/.gem/bin/pod install
```

### Report

* What did you do?
Ran `pod install` after adding `cocoapods-keys` to my `Podfile`.

* What did you expect to happen?
`cocoapods-keys` to request the key, and exit cleanly.

* What happened instead?
The following stack trace

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.5 (14F27)
       Xcode : 7.0.1 (7A1001)
         Git : git version 2.3.8 (Apple Git-58)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fd384d791ce6472307a25da5a4499eef0b096eb8
```

### Plugins

```
cocoapods-keys    : 1.5.2
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
use_frameworks!
link_with 'TraktTopTen', 'TraktTopTenTests'
pod 'SwiftyJSON', '~> 2.3'
pod 'Haneke', '~> 1.0.1'

# Use cocoapods-keys to store the Trakt API key
plugin 'cocoapods-keys', {
  :project => "TraktTopTen",
  :keys => [
    "TraktAPIKey"
  ]}
```

### Error

```
NoMethodError - undefined method `*' for nil:NilClass
/Users/pi/.gem/gems/cocoapods-keys-1.5.2/lib/key_master.rb:32:in `generate_data'
/Users/pi/.gem/gems/cocoapods-keys-1.5.2/lib/key_master.rb:20:in `initialize'
/Users/pi/.gem/gems/cocoapods-keys-1.5.2/lib/plugin.rb:34:in `new'
/Users/pi/.gem/gems/cocoapods-keys-1.5.2/lib/plugin.rb:34:in `setup'
/Users/pi/.gem/gems/cocoapods-keys-1.5.2/lib/plugin.rb:98:in `install!'
/Users/pi/.gem/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/pi/.gem/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Users/pi/.gem/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/pi/.gem/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Users/pi/.gem/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/Users/pi/.gem/bin/pod:23:in `load'
/Users/pi/.gem/bin/pod:23:in `<main>'
```

------ 

After this, I ran `pod install` again, and it exited cleanly:

```
$ pod install
Updating local specs repositories

CocoaPods 0.39.0.rc.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Fetching podspec for `Keys` from `Pods/CocoaPodsKeys`
Downloading dependencies
Using Haneke (1.0.1)
Installing Keys (1.0.0)
Using SwiftyJSON (2.3.0)
Generating Pods project
Integrating client project
Sending stats
Sending stats
```

**Comment by kevboh** [comment]
Also got this. Fresh `pod init` and `pod install` with `cocoapods-keys`.

**Comment by dtrenz** [comment]
Same here. Halp?

**Comment by squarefrog** [comment]
Just run `pod install` again and it should work.

**Comment by kevboh** [comment]
@squarefrog that's what I did, just thought it was worth noting that you weren't alone.

**Comment by squarefrog** [comment]
:+1:

**Comment by dtrenz** [comment]
`pod install` did not fix it for me.

**Comment by dtrenz** [comment]
Here is the line in `key_master.rb` that is causing the error:

```ruby
@data_length = @keys.values.map(&:length).reduce(:+) * (20 + rand(10))
```

It appears that the `*` operator is causing issues.

**Comment by segiddins** [comment]
Yeah, the reduce might need to specify 0 as the seed value

**Comment by cbowns** [comment]
I just hit this as well, with basically the same reproduction steps.

My `gem` versions:

```
% ± cat Gemfile.lock  | grep -i cocoa        
    cocoapods (0.39.0)
      cocoapods-core (= 0.39.0)
      cocoapods-downloader (~> 0.9.3)
      cocoapods-plugins (~> 0.4.2)
      cocoapods-search (~> 0.1.0)
      cocoapods-stats (~> 0.6.2)
      cocoapods-trunk (~> 0.6.4)
      cocoapods-try (~> 0.5.1)
    cocoapods-core (0.39.0)
    cocoapods-downloader (0.9.3)
    cocoapods-keys (1.5.2)
    cocoapods-plugins (0.4.2)
    cocoapods-search (0.1.0)
    cocoapods-stats (0.6.2)
    cocoapods-trunk (0.6.4)
    cocoapods-try (0.5.1)
  cocoapods
  cocoapods-keys
```

**Comment by sasikiran** [comment]
I ran into the same issue. 

### Command

```
/Users/sasikiran/.rvm/gems/ruby-2.2.3/bin/pod install
```

### Report

* What did you do?
Ran pod install after updating the Podfile that supports cocoapods-keys.

* What did you expect to happen?
Expected to save all the keys and complete pod installation.

* What happened instead?
It prompted for all the keys okay, however, the pod installation did not complete and failed with this error.

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
    RubyGems : 2.4.5.1
        Host : Mac OS X 10.11.1 (15B42)
       Xcode : 7.1.1 (7B1005)
         Git : git version 2.4.9 (Apple Git-60)
Ruby lib dir : /Users/sasikiran/.rvm/rubies/ruby-2.2.3/lib
Repositories : master -  @ fatal: Not a git repository (or any of the parent directories): .git
               master-1 - http://github.com/CocoaPods/Specs.git @ 7f93ddecf30035cf4b3b89f657a64b64c406e068
               master-2 - https://github.com/CocoaPods/Specs.git @ c7de2316f04c84e756692338b8dc11c3dd36c217
```

### Plugins

```
cocoapods-keys    : 1.6.0
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

xcodeproj 'SecretProject'

pod 'AFNetworking'
pod 'Fabric'
pod 'Crashlytics'
pod 'SVProgressHUD'
pod 'SSKeychain'

plugin 'cocoapods-keys', {
    :project => "SecretProject",
    :keys => [
    "kLoginBaseURL",
    "kPasswordBaseURL",
    "kClientBaseURL",
    "kAPIScope",
    "kAPIClientId",
    "kAPIClientSecret",
    "kAPIGrantType"
    ]
}
```

### Error

```
NoMethodError - undefined method `*' for nil:NilClass
/Users/sasikiran/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-keys-1.6.0/lib/key_master.rb:32:in `generate_data'
/Users/sasikiran/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-keys-1.6.0/lib/key_master.rb:20:in `initialize'
/Users/sasikiran/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-keys-1.6.0/lib/plugin.rb:34:in `new'
/Users/sasikiran/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-keys-1.6.0/lib/plugin.rb:34:in `setup'
/Users/sasikiran/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-keys-1.6.0/lib/plugin.rb:98:in `install!'
/Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/sasikiran/.rvm/gems/ruby-2.2.3/bin/pod:23:in `load'
/Users/sasikiran/.rvm/gems/ruby-2.2.3/bin/pod:23:in `<main>'
/Users/sasikiran/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/Users/sasikiran/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by pavm035** [comment]
again 'pod install' works for me

**Comment by pavm035** [comment]
How do we avoid this issue when we integrate in CI? How it call twice 'pod install' to correct the issue?
