### ISSUE TITLE
Support for Cocoapods 1.0.0beta

### ISSUE THREAD

**Issue by idokleinman** [orta/cocoapods-keys#129]
I am getting an error when trying to run `pod install` with Cocoapods 1.0.0beta4
```
Fetching podspec for `Keys` from `Pods/CocoaPodsKeys`
[!] No podspec found for `Keys` in `Pods/CocoaPodsKeys`
```

Podfile is
```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'SparkSetupExample-Swift' do 

    xcodeproj 'SparkSetupExample-Swift'
    pod "SparkSetup", :path => "../spark-setup-ios"
    pod "Spark-SDK", :path => "../spark-sdk-ios"
    plugin 'cocoapods-keys', {
        :project => "SparkSetupExample-Swift",
        :keys => [
        "OAuthClientId",
        "OAuthSecret"
        ]}
end
```

Is is a matter of 1.0.0 not yet supported?

**Comment by segiddins** [comment]
See https://github.com/orta/cocoapods-keys/issues/124

**Comment by idokleinman** [comment]
OK, did that, now getting:

### Command

```
/Users/ido/.rvm/gems/ruby-2.3.0/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.0.0.beta.6
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.3 (15D21)
       Xcode : 7.2.1 (7C1002)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /Users/ido/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e7b1668251eac6e78e284ecaf342aa8453759674
```

### Plugins

```
cocoapods-deintegrate : 1.0.0.beta.1
cocoapods-keys        : 1.6.0
cocoapods-plugins     : 1.0.0.beta.1
cocoapods-search      : 1.0.0.beta.1
cocoapods-stats       : 1.0.0.beta.3
cocoapods-trunk       : 1.0.0.beta.2
cocoapods-try         : 1.0.0.beta.3
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

target 'Particle' do
  pod 'Spark-SDK', :path => '../spark-sdk-ios'
  pod 'SparkSetup', :path => '../spark-setup-ios'
  pod 'MBProgressHUD'
  pod 'TSMessages'
  pod 'PullToRefreshCoreText', '~> 0.1'
  pod 'ASValueTrackingSlider'
  pod 'Mixpanel'
  plugin 'cocoapods-keys', {
      :project => "Particle",
      :keys => [
      "MixpanelToken",
      "OAuthClientId",
      "OAuthSecret"
      ]}
end
```

### Error

```
NoMethodError - undefined method `name' for nil:NilClass
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/resolver.rb:456:in `block (2 levels) in spec_is_platform_compatible?'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/resolver.rb:456:in `select'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/resolver.rb:456:in `block in spec_is_platform_compatible?'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/resolver.rb:455:in `each'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/resolver.rb:455:in `all?'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/resolver.rb:455:in `spec_is_platform_compatible?'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/resolver.rb:179:in `requirement_satisfied_by?'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:131:in `block (2 levels) in <class:Resolution>'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:387:in `new_spec_satisfied?'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:375:in `attempt_to_activate_new_spec'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:320:in `attempt_to_activate'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:147:in `process_topmost_state'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:72:in `resolve'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/molinillo-0.4.4/lib/molinillo/resolver.rb:42:in `resolve'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/resolver.rb:62:in `resolve'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer/analyzer.rb:563:in `block in resolve_dependencies'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/user_interface.rb:63:in `section'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer/analyzer.rb:561:in `resolve_dependencies'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer/analyzer.rb:76:in `analyze'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:227:in `analyze'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:151:in `block in resolve_dependencies'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/user_interface.rb:63:in `section'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:150:in `resolve_dependencies'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:114:in `install!'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-keys-1.6.0/lib/plugin.rb:99:in `install!'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/command/update.rb:60:in `run'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/claide-1.0.0.beta.3/lib/claide/command.rb:334:in `run'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/command.rb:50:in `run'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/bin/pod:44:in `<top (required)>'
/Users/ido/.rvm/gems/ruby-2.3.0/bin/pod:23:in `load'
/Users/ido/.rvm/gems/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/ido/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/ido/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by idokleinman** [comment]
anyone?

**Comment by marcelofabri** [comment]
@idokleinman have you tried what the linked issue (#124) says?

> The work around is to remove CocoaPods-Keys from your Podfile do a pod install that then migrates you to 1.0, then add the keys back and pod install again which will work as normal from now on, until CP 2.0.

**Comment by idokleinman** [comment]
yea, I went through that - this is the error I am getting after doing that

**Comment by idokleinman** [comment]
No matter what I try (removing cocoapod-keys, pod install, readding, pod install) I get:

### Command

```
/Users/ido/.rvm/gems/ruby-2.3.0/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.0.0.beta.6
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /Users/ido/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ da403adc9e5ff828ba4a7fd446668890fa528a72
```

### Plugins

```
cocoapods-deintegrate : 1.0.0.beta.1
cocoapods-keys        : 1.6.1
cocoapods-plugins     : 1.0.0.beta.1
cocoapods-search      : 1.0.0.beta.1
cocoapods-stats       : 1.0.0.beta.3
cocoapods-trunk       : 1.0.0.beta.2
cocoapods-try         : 1.0.0.beta.3
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

target 'Particle' do
    pod 'Spark-SDK' #, :path => '../spark-sdk-ios'
    pod 'SparkSetup' #, :path => '../spark-setup-ios'
    pod 'MBProgressHUD'
    pod 'TSMessages'
    pod 'PullToRefreshCoreText', '~> 0.1'
    pod 'ASValueTrackingSlider'
    pod 'Mixpanel'
    plugin 'cocoapods-keys', {
      :project => "Particle",
      :keys => [
      "MixpanelToken",
      "OAuthClientId",
      "OAuthSecret"
      ]}
end
```

### Error

```
NoMethodError - undefined method `name' for nil:NilClass
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/resolver.rb:456:in `block (2 levels) in spec_is_platform_compatible?'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/resolver.rb:456:in `select'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/resolver.rb:456:in `block in spec_is_platform_compatible?'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/resolver.rb:455:in `each'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/resolver.rb:455:in `all?'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/resolver.rb:455:in `spec_is_platform_compatible?'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/resolver.rb:179:in `requirement_satisfied_by?'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:131:in `block (2 levels) in <class:Resolution>'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:387:in `new_spec_satisfied?'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:375:in `attempt_to_activate_new_spec'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:320:in `attempt_to_activate'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:147:in `process_topmost_state'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:72:in `resolve'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/molinillo-0.4.4/lib/molinillo/resolver.rb:42:in `resolve'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/resolver.rb:62:in `resolve'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer/analyzer.rb:563:in `block in resolve_dependencies'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/user_interface.rb:63:in `section'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer/analyzer.rb:561:in `resolve_dependencies'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer/analyzer.rb:76:in `analyze'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:227:in `analyze'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:151:in `block in resolve_dependencies'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/user_interface.rb:63:in `section'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:150:in `resolve_dependencies'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:114:in `install!'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/command/install.rb:37:in `run'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/claide-1.0.0.beta.3/lib/claide/command.rb:334:in `run'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/command.rb:50:in `run'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/bin/pod:44:in `<top (required)>'
/Users/ido/.rvm/gems/ruby-2.3.0/bin/pod:23:in `load'
/Users/ido/.rvm/gems/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/ido/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/ido/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60name%27+for+nil%3ANilClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

➜  photon-tinker-ios git:(master) ✗ pod install
Analyzing dependencies
Downloading dependencies
Using AFNetworking (3.1.0)
Using ASValueTrackingSlider (0.11.2)
Using HexColors (2.2.1)
Using MBProgressHUD (0.9.2)
Using Mixpanel (2.9.6)
Using PullToRefreshCoreText (0.2)
Installing Spark-SDK (0.4.1)
Installing SparkSetup (0.4.0)
Using TSMessages (0.9.12)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 7 dependencies from the Podfile and 9 total pods installed.
➜  photon-tinker-ios git:(master) ✗ pod install
Analyzing dependencies
Fetching podspec for `Keys` from `Pods/CocoaPodsKeys`

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/ido/.rvm/gems/ruby-2.3.0/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.0.0.beta.6
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /Users/ido/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ da403adc9e5ff828ba4a7fd446668890fa528a72
```

### Plugins

```
cocoapods-deintegrate : 1.0.0.beta.1
cocoapods-keys        : 1.6.1
cocoapods-plugins     : 1.0.0.beta.1
cocoapods-search      : 1.0.0.beta.1
cocoapods-stats       : 1.0.0.beta.3
cocoapods-trunk       : 1.0.0.beta.2
cocoapods-try         : 1.0.0.beta.3
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

target 'Particle' do
    pod 'Spark-SDK' #, :path => '../spark-sdk-ios'
    pod 'SparkSetup' #, :path => '../spark-setup-ios'
    pod 'MBProgressHUD'
    pod 'TSMessages'
    pod 'PullToRefreshCoreText', '~> 0.1'
    pod 'ASValueTrackingSlider'
    pod 'Mixpanel'
    plugin 'cocoapods-keys', {
      :project => "Particle",
      :keys => [
      "MixpanelToken",
      "OAuthClientId",
      "OAuthSecret"
      ]}
end
```

### Error

```
NoMethodError - undefined method `name' for nil:NilClass
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/resolver.rb:456:in `block (2 levels) in spec_is_platform_compatible?'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/resolver.rb:456:in `select'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/resolver.rb:456:in `block in spec_is_platform_compatible?'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/resolver.rb:455:in `each'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/resolver.rb:455:in `all?'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/resolver.rb:455:in `spec_is_platform_compatible?'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/resolver.rb:179:in `requirement_satisfied_by?'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:131:in `block (2 levels) in <class:Resolution>'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:387:in `new_spec_satisfied?'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:375:in `attempt_to_activate_new_spec'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:320:in `attempt_to_activate'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:147:in `process_topmost_state'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:72:in `resolve'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/molinillo-0.4.4/lib/molinillo/resolver.rb:42:in `resolve'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/resolver.rb:62:in `resolve'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer/analyzer.rb:563:in `block in resolve_dependencies'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/user_interface.rb:63:in `section'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer/analyzer.rb:561:in `resolve_dependencies'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer/analyzer.rb:76:in `analyze'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:227:in `analyze'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:151:in `block in resolve_dependencies'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/user_interface.rb:63:in `section'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:150:in `resolve_dependencies'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:114:in `install!'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/command/install.rb:37:in `run'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/claide-1.0.0.beta.3/lib/claide/command.rb:334:in `run'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/command.rb:50:in `run'
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/bin/pod:44:in `<top (required)>'
/Users/ido/.rvm/gems/ruby-2.3.0/bin/pod:23:in `load'
/Users/ido/.rvm/gems/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/ido/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/ido/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

Any help will be appreciated.

**Comment by marcelofabri** [comment]
I don't know if it makes a difference, but have you tried adding the `plugin` outside the `target`? This is how it's on [eigen](https://github.com/artsy/eigen/blob/master/Podfile#L11)

**Comment by orta** [comment]
This stack trace doesn't touch CocoaPods keys, it looks to be related to the platform on one of your pods:
```
/Users/ido/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/resolver.rb:456:in `block (2 levels) in spec_is_platform_compatible?'
```
