### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by a8b** [orta/cocoapods-keys#139]
I have following issue:
`➜  ello-ios git:(master) ✗ sudo gem install cocoapods-keys
Password:
Successfully installed cocoapods-keys-1.7.0
Parsing documentation for cocoapods-keys-1.7.0
Done installing documentation for cocoapods-keys after 0 seconds
1 gem installed
➜  ello-ios git:(master) ✗ pod install
```
---------------------------------------------
Error loading the plugin `cocoapods-keys-1.7.0`.

LoadError - cannot load such file -- /Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.7.0/lib/cocoapods_plugin.rb
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:95:in `block in safe_activate_and_require'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:95:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:95:in `safe_activate_and_require'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:30:in `map'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:326:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:325:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:325:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
---------------------------------------------
```
[!] Your Podfile requires that the plugin `cocoapods-keys` be installed. Please install it and try installation again.`

**Comment by louoso** [comment]
Seems the permissions have changed. I was having the same problem and resolved it by running this command `sudo chmod -R go+r /Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.7.0`

**Comment by a8b** [comment]
It solved the issue.

**Comment by orta** [comment]
oh, I wonder if I did a bad deploy - https://github.com/orta/gh_inspector/issues/9

**Comment by kaushalPal86sq** [comment]
@louoso 👍  thanks.  it worked.
