### ISSUE TITLE
Cocoapods-keys doesn't work after upgrading to macOS Sierra

### ISSUE THREAD

**Issue by matmartinez** [orta/cocoapods-keys#143]
Hey there,

I'm having errors when I try to update my pods after installing macOS Sierra. All my other plugins seems alright, it's just `cocoapods-keys` that won't work at all 😢 

I found some issues posted here with similar error messages, none of which seemed to help me.

I'll get this when trying a `pod update`:

```
---------------------------------------------
Error loading the plugin `cocoapods-keys-1.7.0`.

Gem::Ext::BuildError - ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby mkrf_conf.rb
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir': Permission denied - /Library/Ruby/Gems/2.0.0/gems/unf-0.2.0.beta2/ext/gems (Errno::EACCES)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
	from /Library/Ruby/Site/2.0.0/rubygems/installer.rb:619:in `verify_gem_home'
	from /Library/Ruby/Site/2.0.0/rubygems/installer.rb:740:in `pre_install_checks'
	from /Library/Ruby/Site/2.0.0/rubygems/installer.rb:213:in `install'
	from /Library/Ruby/Site/2.0.0/rubygems/resolver/specification.rb:78:in `install'
	from /Library/Ruby/Site/2.0.0/rubygems/request_set.rb:206:in `block in install_into'
	from /Library/Ruby/Site/2.0.0/rubygems/request_set.rb:198:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/request_set.rb:198:in `install_into'
	from /Library/Ruby/Site/2.0.0/rubygems/request_set.rb:119:in `install'
	from /Library/Ruby/Site/2.0.0/rubygems/dependency_installer.rb:389:in `install'
	from mkrf_conf.rb:15:in `<main>'

rake failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/unf-0.2.0.beta2 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-16/2.0.0/unf-0.2.0.beta2/gem_make.out

/Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:89:in `run'
/Library/Ruby/Site/2.0.0/rubygems/ext/rake_builder.rb:13:in `build'
/Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:161:in `block (2 levels) in build_extension'
/Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:160:in `chdir'
/Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:160:in `block in build_extension'
/Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:159:in `synchronize'
/Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:159:in `build_extension'
/Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:198:in `block in build_extensions'
/Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:195:in `each'
/Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:195:in `build_extensions'
/Library/Ruby/Site/2.0.0/rubygems/specification.rb:1436:in `block in build_extensions'
/Library/Ruby/Site/2.0.0/rubygems/user_interaction.rb:45:in `use_ui'
/Library/Ruby/Site/2.0.0/rubygems/specification.rb:1434:in `build_extensions'
/Library/Ruby/Site/2.0.0/rubygems/stub_specification.rb:60:in `build_extensions'
/Library/Ruby/Site/2.0.0/rubygems/basic_specification.rb:56:in `contains_requirable_file?'
/Library/Ruby/Site/2.0.0/rubygems/specification.rb:925:in `block in find_inactive_by_path'
/Library/Ruby/Site/2.0.0/rubygems/specification.rb:924:in `each'
/Library/Ruby/Site/2.0.0/rubygems/specification.rb:924:in `find'
/Library/Ruby/Site/2.0.0/rubygems/specification.rb:924:in `find_inactive_by_path'
/Library/Ruby/Site/2.0.0/rubygems.rb:185:in `try_activate'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
/Library/Ruby/Gems/2.0.0/gems/RubyInline-3.12.4/lib/inline.rb:509:in `load_cache'
/Library/Ruby/Gems/2.0.0/gems/RubyInline-3.12.4/lib/inline.rb:855:in `inline'
/Library/Ruby/Gems/2.0.0/gems/osx_keychain-1.0.0/lib/osx_keychain.rb:17:in `<class:OSXKeychain>'
/Library/Ruby/Gems/2.0.0/gems/osx_keychain-1.0.0/lib/osx_keychain.rb:6:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.7.0/lib/keyring.rb:1:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.7.0/lib/cocoapods_plugin.rb:1:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
/Users/MatMartinez/.gem/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:95:in `block in safe_activate_and_require'
/Users/MatMartinez/.gem/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:95:in `each'
/Users/MatMartinez/.gem/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:95:in `safe_activate_and_require'
/Users/MatMartinez/.gem/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
/Users/MatMartinez/.gem/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:30:in `map'
/Users/MatMartinez/.gem/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
/Users/MatMartinez/.gem/gems/claide-1.0.0/lib/claide/command.rb:326:in `block in run'
/Users/MatMartinez/.gem/gems/claide-1.0.0/lib/claide/command.rb:325:in `each'
/Users/MatMartinez/.gem/gems/claide-1.0.0/lib/claide/command.rb:325:in `run'
/Users/MatMartinez/.gem/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/MatMartinez/.gem/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/MatMartinez/.gem/bin/pod:23:in `load'
/Users/MatMartinez/.gem/bin/pod:23:in `<main>'
---------------------------------------------

Update all pods
Re-creating CocoaPods due to major version update.
[!] Your Podfile requires that the plugin `cocoapods-keys` be installed. Please install it and try installation again.
```

I hope I'm just dumb and this is an easy fix.

Thanks for the help,
Matías.

**Comment by segiddins** [comment]
Did you check `/Library/Ruby/Gems/2.0.0/extensions/universal-darwin-16/2.0.0/unf-0.2.0.beta2/gem_make.out` for any clues what might've gone wrong?

**Comment by matmartinez** [comment]
@segiddins hi, I'm pretty clueless about Ruby, but this is it:

```/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby mkrf_conf.rb
Building native extensions.  This could take a while...
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1381:in `initialize': Permission denied - /Library/Ruby/Gems/2.0.0/gems/unf-0.2.0.beta2/lib/unf_ext/version.rb (Errno::EACCES)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1381:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1381:in `block in copy_file'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1380:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1380:in `copy_file'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1348:in `copy'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:463:in `block in copy_entry'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1485:in `call'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1485:in `wrap_traverse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1488:in `block in wrap_traverse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1487:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1487:in `wrap_traverse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1488:in `block in wrap_traverse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1487:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1487:in `wrap_traverse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:460:in `copy_entry'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:435:in `block in cp_r'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1558:in `block in fu_each_src_dest'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1572:in `fu_each_src_dest0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1556:in `fu_each_src_dest'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:434:in `cp_r'
	from mkrf_conf.rb:18:in `<main>'

rake failed, exit code 1
```

Thanks.

**Comment by matmartinez** [comment]
Quick update: I fixed it with [rbenv](https://github.com/rbenv/rbenv). I'm closing this right now. Thanks for the help =)
