### ISSUE TITLE
Can't store password in Keychain

### ISSUE THREAD

**Issue by michalseverin27** [orta/cocoapods-keys#148]
Hello,

I tried pod install and when set first value for key, terminal print out this issue: Can't store password in Keychain.

I can't find any help.

Any ideas/tips, please?

**Comment by orta** [comment]
that's the exact error message? Can you please give all of the output, otherwise I'm stumped and it's general "do you have a keychain set up" questions

**Comment by michalseverin27** [comment]
I installed under Jenkins user - with admin user is everything ok. 
Thank you.

**Comment by Mattimus333** [comment]
I'm also having the same issue.  Pod install, asked for a key, enter it and then I get these errors:

```RuntimeError - Can't store password in Keychain
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/osx_keychain-1.0.2/lib/osx_keychain.rb:10:in `set'
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/osx_keychain-1.0.2/lib/osx_keychain.rb:10:in `[]='
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-keys-2.0.2/lib/keyring.rb:34:in `save'
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-keys-2.0.2/lib/pod/command/keys/set.rb:45:in `run'
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-keys-2.0.2/lib/preinstaller.rb:65:in `block in setup'
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-keys-2.0.2/lib/preinstaller.rb:43:in `each'
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-keys-2.0.2/lib/preinstaller.rb:43:in `setup'
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-keys-2.0.2/lib/plugin.rb:17:in `setup'
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-keys-2.0.2/lib/plugin.rb:11:in `block in singleton class'
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0/lib/cocoapods/hooks_manager.rb:109:in `block (3 levels) in run'
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0/lib/cocoapods/user_interface.rb:142:in `message'
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0/lib/cocoapods/hooks_manager.rb:103:in `block (2 levels) in run'
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0/lib/cocoapods/hooks_manager.rb:101:in `each'
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0/lib/cocoapods/hooks_manager.rb:101:in `block in run'
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0/lib/cocoapods/user_interface.rb:142:in `message'
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0/lib/cocoapods/hooks_manager.rb:100:in `run'
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:424:in `run_plugins_pre_install_hooks'
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:139:in `block in prepare'
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0/lib/cocoapods/user_interface.rb:142:in `message'
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:135:in `prepare'
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:115:in `install!'
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0/lib/cocoapods/command/install.rb:41:in `run'
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0/lib/cocoapods/command.rb:52:in `run'
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0/bin/pod:55:in `<top (required)>'
/Users/Matt/.rvm/rubies/ruby-2.4.1/bin/pod:23:in `load'
/Users/Matt/.rvm/rubies/ruby-2.4.1/bin/pod:23:in `<main>'
/Users/Matt/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/Users/Matt/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'```

Any help would be appreciated.  Been searching for a solution to this for a while now.

**Comment by ashfurrow** [comment]
@Mattimus333 looks like the `osx_keychain` gem is crashing on this line: 

https://github.com/seattlerb/osx_keychain/blob/51f6d606fb53c31746f3d434654a6c314decc3e4/lib/osx_keychain.rb#L109

Nothing immediate jumps out to me. It sounds like there's something wrong with your keychain. Is it unlocked? Do you have a keychain named `login`? Poke around Keychain Access.app on you Mac and see if anything looks out of place. Good luck!

**Comment by Mattimus333** [comment]
Thanks man.   I'm not very familiar with keychain access but I'll see what I can do.  I do have a login keychain.  I put an issue in over at osx_keychain, maybe they can help.  Appreciate your time!
