### ISSUE TITLE
pod install error: NoMethodError 

### ISSUE THREAD

**Issue by wen0317** [orta/cocoapods-keys#161]
I was able to run **pod install** without any error, but I ran into this error from last week.
I had tried to reinstall and upgrade cocoapods-keys to 2.0.0, but it didn't work for me. 

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.1 (8B62)
         Git : git version 2.10.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e0a9196c6f6ef0d3bd35280b5745f7524f0d29a2
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-keys        : 1.7.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Error

```
NoMethodError - undefined method `[]' for false:FalseClass
/Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.7.0/lib/keyring.rb:14:in `from_hash'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.7.0/lib/keyring_liberator.rb:66:in `get_keyring_at_path'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.7.0/lib/keyring_liberator.rb:60:in `block in get_all_keyrings'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.7.0/lib/keyring_liberator.rb:59:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.7.0/lib/keyring_liberator.rb:59:in `get_all_keyrings'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.7.0/lib/keyring_liberator.rb:28:in `get_current_keyring'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.7.0/lib/preinstaller.rb:23:in `setup'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.7.0/lib/plugin.rb:17:in `setup'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.7.0/lib/plugin.rb:11:in `block in singleton class'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/hooks_manager.rb:109:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/hooks_manager.rb:109:in `block (3 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/hooks_manager.rb:103:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/hooks_manager.rb:101:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/hooks_manager.rb:101:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/hooks_manager.rb:100:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:463:in `run_plugins_pre_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:135:in `block in prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:131:in `prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:109:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by tdangsporttrade** [comment]
I am facing the same issue, have you found a solution yet? Thanks
