### ISSUE TITLE
 CocoaPods-Keys has detected a keys mismatch for your setup.

### ISSUE THREAD

**Issue by AhmedAskar** [orta/cocoapods-keys#194]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin16]
    RubyGems : 2.7.6
        Host : Mac OS X 10.14 (18A391)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.15.2 (Apple Git-101.1)
Ruby lib dir : /usr/local/Cellar/ruby/2.5.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ bdeafd39da58cdebb6ce150ec0e13ffd80cdfa6a
               vodafone-ios-cocoapods - https://df84987aaacb902dbb7582e79ce5cd60195bd13c@github.vodafone.com/TSS-MyVodafone-CoreApp/iOS-CocoaPods.git @ 56d002e4de7980dfb78776ef5de6d8e33459a39e
               vodafone-ios-cocoapods-4.2 - https://df84987aaacb902dbb7582e79ce5cd60195bd13c@github.vodafone.com/TSS-MyVodafone-CoreApp/iOS-CocoaPods-4.2.git @ 8a4513657bf9c59ab388e7c2011480a54f5963c7
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-keys        : 2.1.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://df84987aaacb902dbb7582e79ce5cd60195bd13c@github.vodafone.com/TSS-MyVodafone-CoreApp/iOS-CocoaPods-4.2.git'

target 'MyVodafone-Gold' do
    use_frameworks!
    pod 'Fabric'# , '~> 1.6.11'
    pod 'Crashlytics'#, '~> 3.8.4'
    pod 'UrbanAirship-iOS-SDK'#, '9.2.0'
    pod 'mPulse'#, '~> 2.0.5'
    #pod 'SplunkMint'#, '~> 5.2.0'
    pod 'AdobeMobileSDK'#, '~> 4.13.5'
    pod 'R.swift'#, '~> 3.3.0'
    pod 'Alamofire'#, '~> 4.5.0' # is elegant HTTP Networking
    pod 'Log'#, '~> 1.0.0' # is an extensible logging framework
    pod 'Nuke'#, '~> 5.1.1' # is a powerful image loading and caching framework
    pod 'CryptoSwift'#, '~> 0.7.2' # is a growing collection of standard and secure cryptographic algorithms
    pod 'Reusable'#, '~> 4.0.0' # is a Swift mixin for reusing views easily and in a type-safe way

    pod 'VFGNeedHelp', '2.0.2’
    pod 'VFGSplash', '2.0.9'
    pod 'VFGCommonUI','2.2.7'
    pod 'VFGCommonUtils','2.2.3'
    pod 'VFGNetPerform', '3.1.1'

    pod 'iCarousel'
    pod 'YLProgressBar'#, '~> 3.10.1'
    pod 'ObjectMapper'#, '~> 2.2'
    pod 'AlamofireObjectMapper'#, '~> 4.0'
    pod 'KeychainSwift'#, '~> 8.0'
    pod 'SDWebImage'#, '~> 4.0'
    pod 'ActionSheetPicker-3.0'
    pod 'FSPagerView'#, '0.7.2'
    pod 'M13Checkbox'#, '3.2.2'
    # pod 'SwiftCSVExport'#, '~>2.0.1'
#    pod 'SearchTextField'#, '1.0.2'
    pod 'SearchTextField'#, '1.1.8'
    pod 'netfox'#, '1.11.0' # upgrading to version 1.11.1 causes the request in app to return connection timeout .. no further upgrading to this pod is needed untill they resolve the issue
    pod 'IncrementableLabel' #, '~> 1.2.0'

    pod 'SkeletonView' #, '1.2.1'
end

target 'MyVodafone-GoldTests' do
    inherit! :search_paths
    # Pods for testing
end

plugin 'cocoapods-keys', {
    :project => "MyVodafone-Gold",
    :target => "MyVodafone-Gold",
    :keys => [
    "UrbanAirShipDevelopmentAppKey",
    "UrbanAirShipProductionAppKey",
    "UrbanAirShipProductionAppSecret",
    "UrbanAirShipDevelopmentAppSecret",
    "MPluseApiKey",
    "MintApiKey",
    "ContentType",
    "xapikeySt",
    "xapikeySit",
    "xapikeyEnv03",
    "xapikeyEnv05",
    "WebUser",
    "channel",
    ]
}
```

### Error

```
RuntimeError - Can't store password in Keychain
/usr/local/lib/ruby/gems/2.5.0/gems/osx_keychain-1.0.2/lib/osx_keychain.rb:10:in `set'
/usr/local/lib/ruby/gems/2.5.0/gems/osx_keychain-1.0.2/lib/osx_keychain.rb:10:in `[]='
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-keys-2.1.0/lib/keyring.rb:34:in `save'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-keys-2.1.0/lib/pod/command/keys/set.rb:46:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-keys-2.1.0/lib/preinstaller.rb:65:in `block in setup'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-keys-2.1.0/lib/preinstaller.rb:43:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-keys-2.1.0/lib/preinstaller.rb:43:in `setup'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-keys-2.1.0/lib/plugin.rb:17:in `setup'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-keys-2.1.0/lib/plugin.rb:11:in `block in singleton class'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/hooks_manager.rb:122:in `block (3 levels) in run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:145:in `message'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/hooks_manager.rb:116:in `block (2 levels) in run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/hooks_manager.rb:115:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/hooks_manager.rb:115:in `block in run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:145:in `message'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/hooks_manager.rb:114:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:468:in `run_plugins_pre_install_hooks'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:159:in `block in prepare'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:145:in `message'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:155:in `prepare'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:135:in `install!'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Can%27t+store+password+in+Keychain&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new

**Comment by AhmedAskar** [comment]
i tried pod install the it gives me 
 CocoaPods-Keys has detected a keys mismatch for your setup.
 What is the key for UrbanAirShipDevelopmentAppKey
 > hUlqs_UTSjK490iOXr-MSA

**Comment by AhmedAskar** [comment]
@ashfurrow

**Comment by AhmedAskar** [comment]
@orta

**Comment by sudeepdino008** [comment]
any update on this? Facing this issue on jenkins CLI

**Comment by orta** [comment]
Nope, you're free to look into it

**Comment by gnou** [comment]
If you're running into this issue during remote action (CI/CD, command line, ssh, etc), try to run the same script first as a on-site user (Mac attached on a monitor, or use screen sharing app), there might be a popup to ask permission to access Keychain.

**Comment by WZBbiao** [comment]
try run `sudo pod install`
