### ISSUE TITLE
1.0.0 Error loading the plugin with path

### ISSUE THREAD

**Issue by ruddfawcett** [orta/cocoapods-keys#20]
Just stumbled on this and love it!

I found #18, and built 1.0.0 with the standard `gem build`, and the new commands work, but I get the following error.

I am using latest CocoaPods, Ruby and CL Tools.

Any suggestions?

```
---------------------------------------------
Error loading the plugin with path `/Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.0.0/lib/cocoapods_plugin.rb`.

ArgumentError - wrong number of arguments (2 for 1)
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/hooks_manager.rb:31:in `register'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.0.0/lib/plugin.rb:3:in `<module:CocoaPodsKeys>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.0.0/lib/plugin.rb:1:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.0.0/lib/cocoapods_plugin.rb:3:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:121:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:121:in `require'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command/plugins_helper.rb:104:in `safe_require'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command/plugins_helper.rb:32:in `block in load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command/plugins_helper.rb:31:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command/plugins_helper.rb:31:in `load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:265:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
---------------------------------------------
```

**Comment by RuiAAPeres** [comment]
@ruddfawcett what do you mean by deleting the key? I removed it completely and it didn't work and also passed an empty key, which didn't work as well.

**Comment by ruddfawcett** [comment]
@RuiAAPeres I meant delete the string `'cocoapods-keys', ` from the initializer in plugin.rb.  This allowed you to use the gem without the latest CocoaPods (at the time CP .35(?)).

That worked as of 2 months ago, but I haven't used any API keys in projects since then, so I can't attest to the current state.
