### ISSUE TITLE
pod install error with cocoa pods keys in Pod file

### ISSUE THREAD

**Issue by subhajit-dine** [orta/cocoapods-keys#221]
Report
What did you do?
ℹ Please replace these two lines with what you did.
e.g. Run pod install

What did you expect to happen?
ℹ Please replace these two lines with what you expected to happen.
e.g. Install all pod dependencies correctly.

What happened instead?
Command
/usr/local/bin/pod install
Report
What did you do?

What did you expect to happen?

What happened instead?

Stack
   CocoaPods : 1.11.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.2.26
        Host : Mac OS X 10.15.6 (19G2021)
       Xcode : 12.4 (12D4e)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
Plugins
cocoapods-deintegrate : 1.0.5
cocoapods-keys        : 2.2.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0

NoMethodError - undefined method `[]' for false:FalseClass
/Library/Ruby/Gems/2.6.0/gems/cocoapods-keys-2.2.1/lib/keyring.rb:14:in `from_hash'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-keys-2.2.1/lib/keyring_liberator.rb:66:in `get_keyring_at_path'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-keys-2.2.1/lib/keyring_liberator.rb:60:in `block in get_all_keyrings'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-keys-2.2.1/lib/keyring_liberator.rb:59:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-keys-2.2.1/lib/keyring_liberator.rb:59:in `get_all_keyrings'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-keys-2.2.1/lib/keyring_liberator.rb:28:in `get_current_keyring'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-keys-2.2.1/lib/preinstaller.rb:23:in `setup'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-keys-2.2.1/lib/plugin.rb:17:in `setup'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-keys-2.2.1/lib/plugin.rb:11:in `block in singleton class'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/hooks_manager.rb:122:in `block (3 levels) in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/user_interface.rb:149:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/hooks_manager.rb:116:in `block (2 levels) in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/hooks_manager.rb:115:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/hooks_manager.rb:115:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/user_interface.rb:149:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/hooks_manager.rb:114:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:606:in `run_plugins_pre_install_hooks'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:226:in `block in prepare'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/user_interface.rb:149:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:222:in `prepare'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:160:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:25:in `load'
/usr/local/bin/pod:25:in `<main>'

ℹ Please replace these two lines with of what happened instead.  
error. Pod not installed

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by orta** [comment]
Sounds like a legit bug, you're welcome to take a look and send a PR 👍🏻
