### ISSUE TITLE
pod install fails when `cocoapods-keys` is install (new bug)

### ISSUE THREAD

**Issue by esttorhe** [orta/cocoapods-keys#42]
### Command

```
/Users/creegan/.rvm/gems/ruby-2.1.2/bin/pod install
```

### Report

* What did you do?
  Ran `pod install`

* What did you expect to happen?
  "Installation" of all `pods` and the initialization of the `cocoapods-keys`

* What happened instead?
  `pod install` crashed after installing all the `pods`

### Stack

```
   CocoaPods : 0.36.0
        Ruby : ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.10.3 (14D87h)
       Xcode : 6.1.1 (6A2008a)
         Git : git version 2.2.1
Ruby lib dir : /Users/creegan/.rvm/rubies/ruby-2.1.2/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ 0ac451b4b5ad3b6251c77663014b51a0048dde7e
               master - git://github.com/CocoaPods/Specs.git @ 6f4cd6159d34d7a04e9d3caa16c9ac02d37788bc
               master-1 - https://github.com/CocoaPods/Specs.git @ b2e4f75408a042a029811a9e61dd512018f4a269
```

### Plugins

```
cocoapods-browser : 0.1.5
cocoapods-keys    : 1.0.1
cocoapods-plugins : 0.4.1
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
platform :ios, '7.1'

source 'https://github.com/CocoaPods/Specs.git'

# ignore all warnings from all pods
inhibit_all_warnings!

xcodeproj 'ProjectName'

pod 'CocoaLumberjack', '~> 1.9.2'
pod 'KZAsserts', '~> 1.0'
pod 'ReactiveCocoa'
pod 'ReactiveViewModel'
pod 'MBProgressHUD'
pod 'libextobjc'
pod 'ECSlidingViewController', '~> 2.0.3'
pod 'TSMessages', '~> 0.9.11'
pod 'NSString-Email', '~> 0.0.3'
pod 'TTTAttributedLabel'
pod 'ETFormatter', '~> 1.0'
pod 'ETAssert', '~> 1.0.1'
pod 'ECSlidingViewController', '~> 2.0.3'
pod 'MustOverride', '~> 1.1'

target 'ProjectNameTests', :exclusive => true do
  pod 'Specta', '~> 0.2.1'
  pod 'Expecta+Snapshots', '~> 1.2.1'
end

plugin 'cocoapods-keys', {
	:project => "ProjectName",
	:keys => [
	"OAuthClientSecret",
	"OAuthClientId"
	]
}

class ::Pod::Generator::Acknowledgements
  def header_text
    "ProjectName uses 'CocoaPods' to link with the following 3rd Party Libraries:"
  end
end
```

### Error

```
NoMethodError - undefined method `*' for nil:NilClass
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-keys-1.0.1/lib/key_master.rb:22:in `generate_data'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-keys-1.0.1/lib/key_master.rb:13:in `initialize'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-keys-1.0.1/lib/plugin.rb:8:in `new'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-keys-1.0.1/lib/plugin.rb:8:in `podspec_for_current_project'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-keys-1.0.1/lib/plugin.rb:66:in `from_string'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-core-0.36.0/lib/cocoapods-core/specification.rb:536:in `from_file'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/external_sources/abstract_external_source.rb:142:in `store_podspec'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/external_sources/abstract_external_source.rb:112:in `block in pre_download'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/user_interface.rb:70:in `titled_section'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/external_sources/abstract_external_source.rb:99:in `pre_download'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:347:in `fetch_external_source'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:324:in `block (2 levels) in fetch_external_sources'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:323:in `each'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:323:in `block in fetch_external_sources'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/user_interface.rb:49:in `section'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:322:in `fetch_external_sources'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:57:in `analyze'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:189:in `analyze'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:111:in `block in resolve_dependencies'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/user_interface.rb:49:in `section'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:110:in `resolve_dependencies'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:90:in `install!'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-keys-1.0.1/lib/plugin.rb:40:in `install!'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/command.rb:46:in `run'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/bin/pod:44:in `<top (required)>'
/Users/creegan/.rvm/gems/ruby-2.1.2/bin/pod:23:in `load'
/Users/creegan/.rvm/gems/ruby-2.1.2/bin/pod:23:in `<main>'
/Users/creegan/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/creegan/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

---

I do have the keys specified on my `Podfile` like this:

```ruby
plugin 'cocoapods-keys', {
	:project => "ProjectName",
	:keys => [
	"OAuthClientSecret",
	"OAuthClientId"
	]
}
```

---

*__This was reported on #34 but ~~@orta~~@ashfurrow mentioned this is a new issue and it would be better to open a new issue; hence this one__*

**Comment by esttorhe** [comment]
Ok; adding some new findings on this issue.
My current configuration is similar to `Artsy`'s as in I'm also using a `Makefile` and a `Gemfile`.

If I run `bundle exec pod install` it crashes even if I set the keys on the `Podfile`; but running this
```console
bundle exec pod keys set "OAuthClientSecret" "Value"
bundle exec pod keys set "OAuthClientId" "Value"
```

and then running 
```console
bundle exec pod install
```

Works as expected; perhaps there's something awry going on with how I'm setting the keys on the `Podfile` (although it seems pretty straightforward :flushed: )

**Comment by esttorhe** [comment]
I can confirm this "fixes" the issue (as a workaround though).
Cloning the repo and then running
```console
make bootstrap
```
Downloads everything and by the time it reaches `pod install` crashes horribly even though the keys were specified on the `Podfile` as suggested in the [doc](https://github.com/orta/cocoapods-keys#usage-via-cocoapods-036).
If I immediately after the crash run
```console
bundle exec pod keys set "OAUthClientSecret" "Value"
bundle exec pod keys set "OAUthClientId" "Value"
```

And then run `make bundle` everything works as expected and the `Keys` file is generated as expected.

Hope this helps :bow: 
Thanks again :ok_hand:

**Comment by orta** [comment]
Assigning to @ashfurrow - until next week, when I can take a look

**Comment by ashfurrow** [comment]
I'll take a look tomorrow. Could you post the contents of your Gemfile.lock file?

**Comment by esttorhe** [comment]
Sure; here it is:

---

```ruby
GIT
  remote: https://github.com/CocoaPods/Xcodeproj.git
  revision: fb487113a702e7d85d38d80bbe47076129d0eab7
  specs:
    xcodeproj (0.23.0)
      activesupport (>= 3)
      colored (~> 1.2)

GIT
  remote: https://github.com/esttorhe/SBConstants.git
  revision: 14a408efef7c009e0192c0b94cf4968864d9fab5
  branch: feature-option-to-remove-space
  specs:
    sbconstants (1.0.0)

GEM
  remote: https://rubygems.org/
  specs:
    RubyInline (3.12.3)
      ZenTest (~> 4.3)
    ZenTest (4.11.0)
    activesupport (4.2.0)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    claide (0.8.1)
    cocoapods (0.36.0)
      activesupport (>= 3.2.15)
      claide (~> 0.8.1)
      cocoapods-core (= 0.36.0)
      cocoapods-downloader (~> 0.8.1)
      cocoapods-plugins (~> 0.4.1)
      cocoapods-trunk (~> 0.6.0)
      cocoapods-try (~> 0.4.3)
      colored (~> 1.2)
      escape (~> 0.0.4)
      molinillo (~> 0.2.1)
      nap (~> 0.8)
      open4 (~> 1.3)
      xcodeproj (~> 0.23.0)
    cocoapods-browser (0.1.5)
      cocoapods
    cocoapods-core (0.36.0)
      activesupport (>= 3.2.15)
      fuzzy_match (~> 2.0.4)
      nap (~> 0.8.0)
    cocoapods-downloader (0.8.1)
    cocoapods-keys (1.0.1)
      osx_keychain
    cocoapods-plugins (0.4.1)
      nap
    cocoapods-trunk (0.6.0)
      nap (>= 0.8)
      netrc (= 0.7.8)
    cocoapods-try (0.4.3)
    colored (1.2)
    escape (0.0.4)
    fuzzy_match (2.0.4)
    i18n (0.7.0)
    json (1.8.2)
    minitest (5.5.1)
    molinillo (0.2.1)
    nap (0.8.0)
    netrc (0.7.8)
    open4 (1.3.4)
    osx_keychain (1.0.0)
      RubyInline (~> 3)
    thread_safe (0.3.5)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    xcpretty (0.1.8)

PLATFORMS
  ruby

DEPENDENCIES
  cocoapods
  cocoapods-browser
  cocoapods-core
  cocoapods-keys
  sbconstants!
  xcodeproj!
  xcpretty
```

**Comment by ashfurrow** [comment]
Looking into this now.

**Comment by genadyo** [comment]
I'm having a similar problem when cocoapods-keys installed (this specific project not using it).
```
NoMethodError - undefined method `[]' for nil:NilClass
/Users/genady/.rvm/gems/ruby-2.2.0/gems/cocoapods-keys-1.0.1/lib/plugin.rb:6:in `podspec_for_current_project'
/Users/genady/.rvm/gems/ruby-2.2.0/gems/cocoapods-keys-1.0.1/lib/plugin.rb:66:in `from_string'
/Users/genady/.rvm/gems/ruby-2.2.0/gems/cocoapods-core-0.36.0/lib/cocoapods-core/specification.rb:536:in `from_file'
/Users/genady/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/external_sources/abstract_external_source.rb:142:in `store_podspec'
/Users/genady/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/external_sources/abstract_external_source.rb:112:in `block in pre_download'
/Users/genady/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/user_interface.rb:70:in `titled_section'
/Users/genady/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/external_sources/abstract_external_source.rb:99:in `pre_download'
/Users/genady/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/Users/genady/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:347:in `fetch_external_source'
/Users/genady/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:324:in `block (2 levels) in fetch_external_sources'
/Users/genady/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:323:in `each'
/Users/genady/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:323:in `block in fetch_external_sources'
/Users/genady/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/user_interface.rb:49:in `section'
/Users/genady/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:322:in `fetch_external_sources'
/Users/genady/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:57:in `analyze'
/Users/genady/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:189:in `analyze'
/Users/genady/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:111:in `block in resolve_dependencies'
/Users/genady/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/user_interface.rb:49:in `section'
/Users/genady/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:110:in `resolve_dependencies'
/Users/genady/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:90:in `install!'
/Users/genady/.rvm/gems/ruby-2.2.0/gems/cocoapods-keys-1.0.1/lib/plugin.rb:40:in `install!'
/Users/genady/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/genady/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/genady/.rvm/gems/ruby-2.2.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/genady/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/command.rb:46:in `run'
/Users/genady/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/bin/pod:44:in `<top (required)>'
/Users/genady/.rvm/gems/ruby-2.2.0/bin/pod:23:in `load'
/Users/genady/.rvm/gems/ruby-2.2.0/bin/pod:23:in `<main>'
```

**Comment by ashfurrow** [comment]
@genadyo Could your issue be the same as #34? What are the contents of your Podfile?

**Comment by genadyo** [comment]
Adding the cocoapods-keys plugin didn't solve it.

```
platform :ios, '8.0'
inhibit_all_warnings!

pod 'MBProgressHUD'
pod 'VICMAImageView'
#pod 'Reveal-iOS-SDK'

plugin 'cocoapods-keys', {
    :project => "Organizer",
    :keys => [
    ]
}
```

**Comment by ashfurrow** [comment]
OK, so @genadyo that looks like a possibly separate issue. Could you open a new one?

**Comment by ashfurrow** [comment]
Otherwise, I've got the problem pinned down to this line: https://github.com/orta/cocoapods-keys/blob/484436f4bd12d21b9d7973296c5fb6cc4df8c4bc/lib/key_master.rb#L22 On my machine, it's actually failing here: https://github.com/orta/cocoapods-keys/blob/484436f4bd12d21b9d7973296c5fb6cc4df8c4bc/lib/plugin.rb#L7 , saying it can't find `Informative`. Either way, this leads me to believe that the pre-installation checks/prompts aren't being performed.

**Comment by ashfurrow** [comment]
@esttorhe This should be fixed with #44. If you specify my fork in your Gemfile, it should work. Let me know!

**Comment by esttorhe** [comment]
Well; even though @orta already closed and merge it I just wanted to let you know it worked as expected :boom: 

Thanks @ashfurrow :bow: 

I'll keep using your branch until keys 1.0.3 or something like that comes out :smile:

**Comment by orta** [comment]
It's on rubygems :+1: 
```
 ~/s/r/cocoapods-keys  $ rake release
cocoapods-keys 1.0.2 built to pkg/cocoapods-keys-1.0.2.gem.
Tagged v1.0.2.
Pushed git commits and tags.
Pushed cocoapods-keys 1.0.2 to rubygems.org.
```

**Comment by esttorhe** [comment]
oh wow you guys are quick :zap: 

kudos and thanks again :ok_woman:
