### ISSUE TITLE
pod install: undefined method `length' for nil:NilClass

### ISSUE THREAD

**Issue by tkuichooseyou** [orta/cocoapods-keys#50]
I'm getting this error when I try to `pod install` after specifying my keys in my Podfile. I'm using the master branch of cocoapods-keys. Here's the error report:

$ pod install
Hello there, we found too many xcodeprojects. Please give a name for this project.
 > PROJECT
Analyzing dependencies
Pre-downloading: `Keys` from `https://github.com/ashfurrow/empty-podspec.git`
Hello there, we found too many xcodeprojects. Please give a name for this project.
 > PROJECT

### Command

```
/Users/teddyku/.rvm/gems/ruby-2.2.1/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.36.0
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.10.2 (14C1510)
       Xcode : 6.3 (6D543q)
         Git : git version 2.3.2
Ruby lib dir : /Users/teddyku/.rvm/rubies/ruby-2.2.1/lib
Repositories :
               artsy - https://github.com/artsy/Specs.git @ 0ac451b4b5ad3b6251c77663014b51a0048dde7e
               master - https://github.com/CocoaPods/Specs.git @ e354e859bf513c3dd3cd720d31deb544929fa9fa
```

### Plugins

```
cocoapods-keys    : 1.0.2
cocoapods-plugins : 0.4.1
cocoapods-rome    : 0.0.1
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
source 'https://github.com/a2/arex-pods.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'PROJECT' do
  pod 'Firebase', '~> 2.2'
  pod 'Google-Maps-iOS-SDK', '~> 1.9'
  pod 'ReactiveCocoa', '3.0-alpha.3'
  pod 'Argo'
end

target 'PROJECTTests' do
  pod 'Quick', git: 'https://github.com/Quick/Quick.git'
  pod 'Nimble', git: 'https://github.com/Quick/Nimble.git'
end

plugin 'cocoapods-keys', {
  project: "PROJECT",
  keys: [
    "GoogleMapsAPIKey_debug",
    "GoogleMapsAPIKey_release"
  ]
}
```

### Error

```
NoMethodError - undefined method `length' for nil:NilClass
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-keys-1.0.2/lib/key_master.rb:23:in `map'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-keys-1.0.2/lib/key_master.rb:23:in `generate_data'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-keys-1.0.2/lib/key_master.rb:13:in `initialize'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-keys-1.0.2/lib/plugin.rb:10:in `new'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-keys-1.0.2/lib/plugin.rb:10:in `podspec_for_current_project'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-keys-1.0.2/lib/plugin.rb:68:in `from_string'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-core-0.36.0/lib/cocoapods-core/specification.rb:536:in `from_file'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.0/lib/cocoapods/external_sources/abstract_external_source.rb:142:in `store_podspec'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.0/lib/cocoapods/external_sources/abstract_external_source.rb:112:in `block in pre_download'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.0/lib/cocoapods/user_interface.rb:70:in `titled_section'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.0/lib/cocoapods/external_sources/abstract_external_source.rb:99:in `pre_download'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.0/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:347:in `fetch_external_source'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:324:in `block (2 levels) in fetch_external_sources'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:323:in `each'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:323:in `block in fetch_external_sources'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.0/lib/cocoapods/user_interface.rb:49:in `section'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:322:in `fetch_external_sources'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:57:in `analyze'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:189:in `analyze'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:111:in `block in resolve_dependencies'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.0/lib/cocoapods/user_interface.rb:49:in `section'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:110:in `resolve_dependencies'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:90:in `install!'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-keys-1.0.2/lib/plugin.rb:42:in `install!'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.0/lib/cocoapods/command.rb:46:in `run'
/Users/teddyku/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.0/bin/pod:44:in `<top (required)>'
/Users/teddyku/.rvm/gems/ruby-2.2.1/bin/pod:23:in `load'
/Users/teddyku/.rvm/gems/ruby-2.2.1/bin/pod:23:in `<main>'
/Users/teddyku/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/teddyku/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by tkuichooseyou** [comment]
Sorry, I actually found out it was because I started off with manually adding keys, and then switched to the Podfile specified keys. After I removed the original keys with `pod key rm` and did `pod install` then it worked.
