### ISSUE TITLE
`Could not load keyring` for a Podfile that doesn’t use Keys

### ISSUE THREAD

**Issue by saniul** [orta/cocoapods-keys#55]
# Setup
```
$ rm -rf Pods/  
$ rm -rf Podfile.lock
```
```
$ pod --verbose --version
0.36.3
cocoapods-plugins: 0.4.1
cocoapods-try: 0.4.3
cocoapods-trunk: 0.6.0
cocoapods-keys: 1.0.2
```
```
$ cat Podfile 
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

#pod 'Facebook-iOS-SDK' not compatible with frameworks :(

use_frameworks!

pod 'pop', '~> 1.0'
pod 'Reachability', '~> 3.1.0'
pod 'AFNetworking', '~> 2.5'
pod 'BlocksKit', '~> 2.2.5'

pod 'Realm'

#target 'monocle' do
#end

#target 'MNCLData' do
#end

#target 'monocleTests' do
#end
```

# Error
```
$ pod install --verbose
  Preparing

Analyzing dependencies

Updating spec repositories
Updating spec repo `master`
  $ /usr/local/bin/git pull --ff-only
  Current branch master is up to date.

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods`: (``)

Fetching external sources
-> Pre-downloading: `Keys` from `https://github.com/ashfurrow/empty-podspec.git`
 > Git download
 > Git download
     $ /usr/local/bin/git clone https://github.com/ashfurrow/empty-podspec.git /Users/saniul/Projects/Monocle/Monocle/Pods/Keys --single-branch --depth 1
     Cloning into '/Users/saniul/Projects/Monocle/Monocle/Pods/Keys'...
[!] Could not load keyring

/Users/saniul/.rvm/gems/ruby-2.1.1/gems/cocoapods-keys-1.0.2/lib/plugin.rb:9:in `podspec_for_current_project'
/Users/saniul/.rvm/gems/ruby-2.1.1/gems/cocoapods-keys-1.0.2/lib/plugin.rb:68:in `from_string'
/Users/saniul/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-0.36.3/lib/cocoapods-core/specification.rb:536:in `from_file'
/Users/saniul/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.3/lib/cocoapods/external_sources/abstract_external_source.rb:142:in `store_podspec'
/Users/saniul/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.3/lib/cocoapods/external_sources/abstract_external_source.rb:112:in `block in pre_download'
/Users/saniul/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.3/lib/cocoapods/user_interface.rb:70:in `titled_section'
/Users/saniul/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.3/lib/cocoapods/external_sources/abstract_external_source.rb:99:in `pre_download'
/Users/saniul/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.3/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/Users/saniul/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.3/lib/cocoapods/installer/analyzer.rb:347:in `fetch_external_source'
/Users/saniul/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.3/lib/cocoapods/installer/analyzer.rb:324:in `block (2 levels) in fetch_external_sources'
/Users/saniul/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.3/lib/cocoapods/installer/analyzer.rb:323:in `each'
/Users/saniul/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.3/lib/cocoapods/installer/analyzer.rb:323:in `block in fetch_external_sources'
/Users/saniul/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.3/lib/cocoapods/user_interface.rb:49:in `section'
/Users/saniul/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.3/lib/cocoapods/installer/analyzer.rb:322:in `fetch_external_sources'
/Users/saniul/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.3/lib/cocoapods/installer/analyzer.rb:57:in `analyze'
/Users/saniul/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.3/lib/cocoapods/installer.rb:189:in `analyze'
/Users/saniul/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.3/lib/cocoapods/installer.rb:111:in `block in resolve_dependencies'
/Users/saniul/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.3/lib/cocoapods/user_interface.rb:49:in `section'
/Users/saniul/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.3/lib/cocoapods/installer.rb:110:in `resolve_dependencies'
/Users/saniul/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.3/lib/cocoapods/installer.rb:90:in `install!'
/Users/saniul/.rvm/gems/ruby-2.1.1/gems/cocoapods-keys-1.0.2/lib/plugin.rb:42:in `install!'
/Users/saniul/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.3/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/saniul/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.3/lib/cocoapods/command/project.rb:101:in `run'
/Users/saniul/.rvm/gems/ruby-2.1.1/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/saniul/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.3/lib/cocoapods/command.rb:46:in `run'
/Users/saniul/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.3/bin/pod:44:in `<top (required)>'
/Users/saniul/.rvm/gems/ruby-2.1.1/bin/pod:23:in `load'
/Users/saniul/.rvm/gems/ruby-2.1.1/bin/pod:23:in `<main>'
/Users/saniul/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
/Users/saniul/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>’
```

**Comment by ashfurrow** [comment]
Probably due to our use of monkey patching.

**Comment by orta** [comment]
It is, I took a look at this locally, we need to check if there's a `plugin "Keys"` or whatever in the podfile before doing anything.

**Comment by danthorpe** [comment]
@orta @ashfurrow is there a minimum `plugin "cocoa pods-keys"` fragment which can be added to a Podfile to suppress the error and allow the usual `pod install/update` to continue until this issue is resolved?
