### ISSUE TITLE
Keys are always added to a root target

### ISSUE THREAD

**Issue by orta** [orta/cocoapods-keys#62]
![screen shot 2015-04-20 at 10 25 44 am](https://cloud.githubusercontent.com/assets/49038/7232093/9d4f4d88-e747-11e4-9ed0-1c29184611dc.png)

I've looked into this and tried adding [here](https://github.com/orta/cocoapods-keys/blob/master/lib/plugin.rb#L21):

```
      if user_options["target"]
        # Support correct scoping
        podfile.target user_options["target"] do
          podfile.pod 'Keys', :git => 'https://github.com/ashfurrow/empty-podspec.git'
        end

      else
        podfile.pod 'Keys', :git => 'https://github.com/ashfurrow/empty-podspec.git'
      end
```

But that crashes CocoaPods, it's not built to handle something like this in the Podfile:
 
```
target 'Show Notes' do
  pod 'AFNetworking'
end

target 'Show Notes' do
  pod 'Keys', :git => ...
end
```

```
Errno::EEXIST - File exists @ dir_s_mkdir - /Users/orta/dev/ios/Show Notes/Pods/Target Support Files/Pods-Show Notes-Keys
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/installer/target_installer.rb:86:in `mkdir'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/installer/target_installer.rb:86:in `mkdir'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/installer/target_installer.rb:86:in `create_support_files_dir'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:19:in `block in install!'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/user_interface.rb:110:in `message'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:17:in `install!'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/installer.rb:499:in `block (2 levels) in install_libraries'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/installer.rb:496:in `each'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/installer.rb:496:in `block in install_libraries'
```

a look through the [podfile DSL](http://www.rubydoc.info/gems/cocoapods-core/Pod/Podfile/DSL) indicates that I cannot loop through targets? Any ideas?

**Comment by ashfurrow** [comment]
Oh, hmm. Interesting edge case. Could you describe the desired use case a bit more? Why might someone want this scoped?

**Comment by orta** [comment]
Podfiles should look like:

```
target 'Show Notes' do
   [..]
end

target 'Show NotesTests' do
   [...]
end
```

We don't do this in Artsy, mainly due to inertia. But the new DSL will force this pattern. Right now Keys will always create a root Pods and pass it along in that. This broke my projects xcconfig setup from the original targets, and had I not been me, I would have been quite confused about what to do next.

**Comment by ashfurrow** [comment]
Ah, makes sense :clap:
