### ISSUE TITLE
Cannot push a podspec when cocoapods-keys is installed

### ISSUE THREAD

**Issue by andreamazz** [orta/cocoapods-keys#63]
I can't push a new podspec if I have cocoapods-keys installed. Uninstalling the gem solved the issue. (I was using the latest `1.1.0`

### Command

```
/Users/Andrea/.rbenv/versions/2.2.0/bin/pod trunk push AMTagListView.podspec
```

### Stack

```
   CocoaPods : 0.36.3
        Ruby : ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
    RubyGems : 2.4.5
        Host : Mac OS X 10.10.4 (14E7f)
       Xcode : 6.3 (6D570)
         Git : git version 2.2.1
Ruby lib dir : /Users/Andrea/.rbenv/versions/2.2.0/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ 0ac451b4b5ad3b6251c77663014b51a0048dde7e
               master - https://github.com/CocoaPods/Specs.git @ 1e932e45f368b82c0826496f61a3e40a441d3bda
```

### Plugins

```
cocoapods-keys    : 1.1.0
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.3
```

### Error

```
NoMethodError - undefined method `plugins' for nil:NilClass
/Users/Andrea/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-keys-1.1.0/lib/plugin.rb:53:in `validates_for_keys'
/Users/Andrea/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-keys-1.1.0/lib/plugin.rb:47:in `install!'
/Users/Andrea/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.36.3/lib/cocoapods/validator.rb:311:in `install_pod'
/Users/Andrea/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.36.3/lib/cocoapods/validator.rb:215:in `block in perform_extensive_analysis'
/Users/Andrea/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.36.3/lib/cocoapods/validator.rb:211:in `each'
/Users/Andrea/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.36.3/lib/cocoapods/validator.rb:211:in `perform_extensive_analysis'
/Users/Andrea/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.36.3/lib/cocoapods/validator.rb:73:in `validate'
/Users/Andrea/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-trunk-0.6.0/lib/pod/command/trunk/push.rb:109:in `validate_podspec'
/Users/Andrea/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-trunk-0.6.0/lib/pod/command/trunk/push.rb:58:in `run'
/Users/Andrea/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/Andrea/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.36.3/lib/cocoapods/command.rb:46:in `run'
/Users/Andrea/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.36.3/bin/pod:44:in `<top (required)>'
/Users/Andrea/.rbenv/versions/2.2.0/bin/pod:23:in `load'
/Users/Andrea/.rbenv/versions/2.2.0/bin/pod:23:in `<main>'
```

**Comment by ashfurrow** [comment]
Ah, right. Think you were getting this because the gem was installed system-wide, and it (incorrectly) looks for a keys specification in every Podfile. We haven't run into this because we use Gemfiles. We'll get on this shortly, thanks!

**Comment by andreamazz** [comment]
Yep, caught this by chance by pushing to trunk on a machine where cocoapods-keys wasn't installed with bundler.  
Thanks! :+1:

**Comment by orta** [comment]
Interesting, nice catch :+1:

**Comment by abbeycode** [comment]
I'm seeing this too

**Comment by andreamazz** [comment]
:+1: 
Thanks!
