### ISSUE TITLE
Crash when attempting to set a key without first running pod update

### ISSUE THREAD

**Issue by jshier** [orta/cocoapods-keys#88]
### Command

```
/Users/jshier/.rvm/gems/ruby-2.2.2@hazelight/bin/pod keys set APIKey key
```

### Report

* What did you do?
Ran command without first running `pod install` with the key info set in my Podfile.

* What did you expect to happen?
Value to be set in cocoapods-keys.

* What happened instead?
This crash.

### Stack

```
   CocoaPods : 0.37.2
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11 (15A178w)
       Xcode : 7.0 (7A120f)
         Git : git version 2.3.7 (Apple Git-57)
Ruby lib dir : /Users/jshier/.rvm/rubies/ruby-2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 74df35ecf045e68153d5019381c5534928aebf46
```

### Plugins

```
cocoapods-keys    : 1.3.1
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.6.1
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
platform :ios, '9.0'

use_frameworks!

pod 'OHHTTPStubs', '~> 4.0.0'

link_with 'HazeLightTests', 'HazeLightUITests'

target 'HazeLight' do
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'
  pod 'Argo', :git => 'https://github.com/thoughtbot/Argo.git', :branch => 'td-swift-2'
end
```

### Error

```
NameError - uninitialized constant CocoaPodsKeys::NameWhisperer::UI
/Users/jshier/.rvm/gems/ruby-2.2.2@hazelight/gems/cocoapods-keys-1.3.1/lib/name_whisperer.rb:28:in `search_folders_for_xcodeproj'
/Users/jshier/.rvm/gems/ruby-2.2.2@hazelight/gems/cocoapods-keys-1.3.1/lib/name_whisperer.rb:10:in `get_project_name'
/Users/jshier/.rvm/gems/ruby-2.2.2@hazelight/gems/cocoapods-keys-1.3.1/lib/pod/command/keys/set.rb:55:in `current_keyring'
/Users/jshier/.rvm/gems/ruby-2.2.2@hazelight/gems/cocoapods-keys-1.3.1/lib/pod/command/keys/set.rb:41:in `run'
/Users/jshier/.rvm/gems/ruby-2.2.2@hazelight/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/jshier/.rvm/gems/ruby-2.2.2@hazelight/gems/cocoapods-0.37.2/lib/cocoapods/command.rb:46:in `run'
/Users/jshier/.rvm/gems/ruby-2.2.2@hazelight/gems/cocoapods-0.37.2/bin/pod:44:in `<top (required)>'
/Users/jshier/.rvm/gems/ruby-2.2.2@hazelight/bin/pod:23:in `load'
/Users/jshier/.rvm/gems/ruby-2.2.2@hazelight/bin/pod:23:in `<main>'
/Users/jshier/.rvm/gems/ruby-2.2.2@hazelight/bin/ruby_executable_hooks:15:in `eval'
/Users/jshier/.rvm/gems/ruby-2.2.2@hazelight/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by segiddins** [comment]
@jshier just pushed a fix, thanks for reporting!
